# ***********************************************************************
# @license      : BSDv3
# @author       : Andreas Kaeberlein
#
# @maintainer   : Andreas Kaeberlein
# @email        : andreas.kaeberlein@web.de
#
# @file         : doxygen.yml
# @date         : 2024-11-09
# @see          : https://github.com/andkae/SPI-Flash-Circular-Buffer
#
# @brief        : Runs Doxygen and pdf build
#
# **********************************************************************/


name: doxygen

on: push

jobs:
  doxygen:
    runs-on: ubuntu-22.04
    container: dolphinics/doxygen:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Prepare Dirs
        run: |
          mkdir -p ./doxygen/out
      - name: Run Doxygen
        run: |
          doxygen --version
          doxygen ./doxygen/Doxyfile
      - name: Run Latex
        run: |
          pdflatex --version
          (cd ./doxygen/out/latex && make)  # build pdf without path change
          mv ./doxygen/out/latex/refman.pdf ./${{github.event.repository.name}}_ug-${{github.ref_name}}.pdf    # move to top
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: sfcb-ug-${{github.ref_name}}
          path: ${{github.event.repository.name}}_ug-${{github.ref_name}}.pdf
          retention-days: 30
